GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnV0dWphIiwiaWF0IjoxNjAwNjEzMzAzfQ.7h8eNHzgwX6Mz9Yaun4xMiUiDHO3DwpVwrs1296OzpY

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Pallavi",
    "password": "password",
    "post": "Post 1"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "Rutuja",
    "password": "password"
}